### PR TITLE
https

### PR DESCRIPTION
**Pull request by RainySY**

### CODE REVIEW

**Comment by RainySY** [comment]
简单修复了一下因为Https而产生
```python
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Proxy URL had no scheme, should start with http:// or https://
```
```python
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Proxy URL had no scheme, should start with http:// or https://
```
之类的报错

**Comment by Luoofan** [comment]
1. 无法复现
2. 根据所示`should start with http:// or https://`，源代码相关links都是以`http://`开头的，按理来说不存在这种错误
3. 根据对安全性的需求个人可以选择手动改为https

**Review by KevinZonda — APPROVED** [review]

**Comment by KevinZonda** [comment]
> 1. 无法复现
> 2. 根据所示`should start with http:// or https://`，源代码相关links都是以`http://`开头的，按理来说不存在这种错误
> 3. 根据对安全性的需求个人可以选择手动改为https

It's nonsense that still use plain HTTP in 2021.

**Comment by Luoofan** [comment]
> > 1. 无法复现
> > 2. 根据所示`should start with http:// or https://`，源代码相关links都是以`http://`开头的，按理来说不存在这种错误
> > 3. 根据对安全性的需求个人可以选择手动改为https
> 
> It's **nonsense** that still use plain HTTP in 2021.

Hi, @KevinZonda ! 
You're right. It's my mistake not to take this into consideration at the begining.

But, the essential parts, for example, first visit to chaoxing website, logining, watching videos, answering questions, and so on,   are all accessing with **HTTPS**.

The key point is this repository mainly  uses **selenium** library to simulate learning personally rather than **requests** library.
It means that, the mostly event happened during the program running is **clicking**. Therefore, how the program accessing websites by HTTP or HTTPS depends on what the website html code is. In other words, the program behaves like a person visits the websites through clicks because of the selenium library.

And if you visit chaoxing website personally, you maybe find some links will be accessed by HTTP autoly.
So, maybe you should send your words to chaoxing team.

At last but not least, this pull request will be merged after my testing.

**Comment by Luoofan** [comment]
It works well on my account in the case of good network conditions.

Thanks for your pr and comments! @RainySY @KevinZonda

**Comment by KevinZonda** [comment]
Thanks for your reply. It's not related to which library are you using, but considering that Chrome 90 has set HTTPS as default for incomplete links, it will be better that if you could set HTTPS as the default protocol.

Anyway, have a good day. :)

Refer: https://blog.chromium.org/2021/03/a-safer-default-for-navigation-https.html

26 Apr 2021, 09:58 by ***@***.***:

**Comment by KevinZonda** [comment]
Cool! Cheers!

26 Apr 2021, 10:09 by ***@***.***:

**Pull request merged**
